import { Lightbulb } from "lucide-react";

function QuestionNote() {
  return (
    <div className="border rounded-lg p-5 bg-blue-100 mt-20 mb-0">
      <h2 className="flex text-primary items-center gap-2">
        <Lightbulb />
        <strong>Note:</strong>
      </h2>
      <h2 className="text-sm my-2 text-primary">
        Record your answer by clicking record. At the end of interview we will
        give you the feddback along with the most ideal answer for each of the
        question and your answer to compare it.
      </h2>
      <h2 className="text-sm my-2 text-primary">
        <strong>Remember!</strong>
        <br />
        There are no correct answer to any questions as these are generated by
        AI and are based on the most common questions asked in the industry.
        Answer can vary depending upon the situation, candidate and the company
        you are interviewing for.
      </h2>
    </div>
  );
}

export default QuestionNote;
